name: CD Delevery
on:
  pull_request:
    types:
      - opned
      - reopned
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps:
      - name: upload code couverage
      - uses: codecov/codecov-action@v2
