name: CD Delivery

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps:
      - name: Upload code coverage
        run: |
          # Add the command to upload code coverage here
          # Example:
          # codecov --token=<your_token>
        uses: codecov/codecov-action@v2

