
name: Publish stage
on:
  push:
  pull_request:
    types:
      - opned
      - reopned
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    container: 'python:3.9-slim'

    steps:
      - name: upload code couverage
      - uses: codecov/codecov-action@v2
        with:
          version: v0.1.13
