name: Publish stage
on:
  push:
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: 'python:3.9-slim'

    steps:
      - name: Upload code coverage
        uses: codecov/codecov-action@v2
        with:
          version: v0.1.13
